name: Linting

on: [push]

env:
  TERRAFORM_VERSION: '0.12.29'

jobs:
  lint-tf:
    runs-on: ubuntu-latest
    container: linuxbrew/brew:latest

    steps:
    - uses: actions/checkout@v1
    - name: install terraform/grunt
      run: |
        brew install terragrunt

    - name: terraform fmt
      id: terraform
      run: |
        apt update
        apt install wget unzip
        wget -q https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
        unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip -d /bin/
        terraform version
        terraform fmt -check -recursive -diff -no-color

    - name: terragrunt hclfmt
      id: grunt
      run: |
        terragrunt hclfmt --terragrunt-check