name: Linting

on: [push]

jobs:
  lint-tf:
    runs-on: ubuntu-latest
    container: linuxbrew/brew:latest

    steps:
    - uses: actions/checkout@v1
    - name: install terraform/grunt
      run: |
        brew install terraform terragrunt

    - name: terraform fmt
      id: terraform
      run: |
        mkdir ~/terraform
        wget https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip -p ~/terraform
        unzip ~/terraform/terraform_0.12.29_linux_amd64.zip /bin/
        terraform version
        terraform fmt -check -recursive -diff -no-color

    - name: terragrunt hclfmt
      id: grunt
      run: |
        terragrunt hclfmt --terragrunt-check