name: Pipeline test
on:
    push:
      branches:
      - "master"
jobs:
  Pipeline-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: create file
        shell: pwsh
        run: New-Item -Type File -Path thingshappened.txt
      - name: test for file
        shell: pwsh
        if: ${{ test-path thingshappened.txt }}
        run: |
          write-host "things happened!!"
          dir -recurse