name: Linting

on: [push]

jobs:
  lint-tf:
    runs-on: ubuntu-latest
    container: linuxbrew/brew:latest

    steps:
    - name: install terraform/grunt
    - uses: actions/checkout@v1
      run: |
        brew install terraform terragrunt


    - name: Lint Terraform
      id: terraform
      run: terraform fmt -check -recursive -diff -no-color

    - name: Lint Terragrunt
      id: grunt
      run: |
        terragrunt hclfmt --terragrunt-check