name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container: linuxbrew/brew:latest

    steps:
    - uses: actions/checkout@v1
    - name: install terraform/grunt
      run: |
        brew install terraform terragrunt